---
title: "Format `flextable` objects"
author: "David Gohel"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flextable_format}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`flextable` makes possible to create beautiful reporting table from `data.frame`. 

```{r warning=FALSE, message=FALSE}
library(flextable)
library(oxbase)
library(dplyr)

myft <- flextable(head(mtcars)) 
tabwid(myft)
```

## Format table elements

Function `set_style` is changing formatting properties of table elements. 

```{r warning=FALSE, message=FALSE}
myft <- myft %>% 
  set_style(c_b_b(), p_r(padding=2), t_i(color="#50514F") ) %>% 
  set_style(c_b_b(), p_r(padding=5), t_b(color="orange"), part = "header" )
tabwid(myft)
```

Conditional formatting can be made by using the selector arguments.

```{r warning=FALSE, message=FALSE}
myft <- myft %>% 
  set_style(i = ~ drat > 3.5 & wt > 2.6, 
            j = ~ vs + am + gear + carb, 
            t_i(color="cyan") )
tabwid(myft)
```

Conditional formatting can be made by using the selector arguments.

```{r warning=FALSE, message=FALSE}
myft <- myft %>% 
  set_bg(rgb(1, .8, .2, .2), i = ~ drat > 3.5 & wt > 2.6, j = NULL )
tabwid(myft)
```

