---
title: "Introdution to `flextable` objects"
author: "David Gohel"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flextable_introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`flextable` makes possible to create beautiful reporting table from `data.frame`. 

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(flextable)
library(oxbase)
library(dplyr)
iris %>% 
  group_by(Species) %>% 
  do( head(., n = 3) ) %>% 
  flextable(select = c("Species", 
                       "break1", "Sepal.Length", "Sepal.Width", 
                        "break2", "Petal.Length", "Petal.Width") ) %>% 
  set_header(
    Sepal.Length = list("Length", "Sepal"), Sepal.Width = list("Width", "Sepal"),
    Petal.Length = list("Length", "Petal"), Petal.Width = list("Width", "Petal"),
    Species = list("Species", "Species")
    ) %>% 
  style(t_bold(font.size = 12), part = "header") %>% 
  style(pr_text(font.size = 12), part = "body") %>% 
  style(t_bi(font.size = 12), j = ~ Species ) %>% 
  padding(padding = 2, part = "all") %>% 
  border( border.top = pr_border(), part = "all" ) %>% 
  bg(i = ~ seq_along(Petal.Length) %% 2 == 0, bg = "#EFEFEF") %>% 
  border( j = ~ break1 + break2, 
          border.top = b_null(), border.bottom = b_null(), part = "all" ) %>% 
  bg(j = ~ break1 + break2, bg = "transparent", part = "all") %>% 
  autofit() %>% 
  tabwid()
```


```{r warning=FALSE, message=FALSE}
library(flextable)
library(oxbase)
library(dplyr)

myft <- flextable(head(mtcars), select = c("am", "carb", "gear", "mpg", "drat" )) 
tabwid(myft)
```


## Format table elements

Function `style` is changing formatting properties of table elements. 

```{r warning=FALSE, message=FALSE}
myft <- myft %>% 
  style(c_b_b(), p_right(padding=2), part = "all" )
tabwid(myft)
```

Conditional formatting can be made by using the selector arguments.

```{r warning=FALSE, message=FALSE}
myft <- myft %>% 
  style(i = ~ drat > 3.5, j = ~ drat, t_italic(color="#44A530") )
tabwid(myft)
```

## Layout the table and its components

```{r warning=FALSE, message=FALSE}

myft <- myft %>%
  merge_v(j = c("carb", "am") )
tabwid(myft)
```



## Format content

You can use `format_simple`. 

```{r warning=FALSE, message=FALSE}
myft <- myft %>%
  display(
    am = format_simple(format_integer(am)),
    gear = format_simple(format_integer(gear), pr_text_ = t_bold()),
    carb = format_simple(format_integer(carb))
  )

tabwid(myft)
```

And a flexible function `format_that`. 


```{r warning=FALSE, message=FALSE}
myft <- myft %>%
  display(
    mpg = format_that(
        "{{ mpg_ }} mpg (# {{ cyl_ }} cyl.)",
        mpg_ = ftext( format_double(mpg, digits = 1), t_italic() ),
        cyl_ = ftext( format_integer(cyl), t_italic() )
    ) ) %>% autofit() 

tabwid(myft)
```


