# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

a_sptree_open <- function(standalone, id, offx, offy) {
    .Call('flextable_a_sptree_open', PACKAGE = 'flextable', standalone, id, offx, offy)
}

a_graphic_frame_open <- function(id, offx, offy) {
    .Call('flextable_a_graphic_frame_open', PACKAGE = 'flextable', id, offx, offy)
}

a_sptree_close <- function() {
    .Call('flextable_a_sptree_close', PACKAGE = 'flextable')
}

a_graphic_frame_close <- function() {
    .Call('flextable_a_graphic_frame_close', PACKAGE = 'flextable')
}

wml_run_pic <- function(src, width, height) {
    .Call('flextable_wml_run_pic', PACKAGE = 'flextable', src, width, height)
}

