#' @title data summary preparation
#' @description It performs a univariate statistical analysis of a dataset
#' by group and formats the results so that they can be used with
#' the [tabulator()] function.
#' @note
#' This is very first version of the function; be aware it
#' can evolve or change.
#' @param x dataset
#' @param by columns names to be used as grouping columns
#' @param overall_label label to use as overall label
#' @examples
#' z <- summarizor(CO2[-c(1, 4)],
#'   by = "Treatment",
#'   overall_label = "Overall"
#' )
#'
#'
#' # version 1 ----
#' tab_1 <- tabulator(
#'   x = z,
#'   rows = c("variable", "stat"),
#'   cols = "Treatment",
#'   blah = as_paragraph(
#'     as_chunk(
#'       format_summarizor_cols(
#'         stat, data_type,
#'         value, cts, percent
#'       )
#'     )
#'   )
#' )
#'
#' ft_1 <- as_flextable(tab_1)
#' ft_1
#'
#' # version 2 ----
#' n_format <- function(n, percent) {
#'   z <- character(length = length(n))
#'   wcts <- !is.na(n)
#'   z[wcts] <- sprintf("%.0f (%.01f %%)", n[wcts], percent[wcts] * 100)
#'   z
#' }
#' stat_format <- function(value) {
#'   z <- character(length = length(value))
#'   wnum <- !is.na(value)
#'   z[wnum] <- sprintf("%.01f", value[wnum])
#'   z
#' }
#'
#' tab_2 <- tabulator(z,
#'   rows = c("variable", "stat"),
#'   cols = "Treatment",
#'   `Est.` = as_paragraph(as_chunk(value)),
#'   `N` = as_paragraph(as_chunk(n_format(cts, percent)))
#' )
#'
#' ft_2 <- as_flextable(tab_2)
#' ft_2
#' @section Illustrations:
#' ft_1:
#'
#' \if{html}{\figure{fig_summarizor_1.png}{options: width=70\%}}
#'
#' ft_2:
#'
#' \if{html}{\figure{fig_summarizor_2.png}{options: width=70\%}}
#'
#' @export
summarizor <- function(x, by = character(), overall_label = NULL){

  stopifnot(`by can not be empty` = length(by)>0)

  x <- as.data.frame(x)

  last_by <- by[length(by)]
  if(length(last_by) > 0 && !is.null(overall_label) ){
    xoverall <- x
    z <- xoverall[[last_by]]
    levels_ <- if(is.factor(z)){
      c(levels(z), overall_label)
    } else {
      c(sort(unique(z)), overall_label)
    }
    z <- rep(overall_label, nrow(xoverall))
    xoverall[[last_by]] <- z
    x <- rbind(x, xoverall)

    x[[last_by]] <- factor(x[[last_by]], levels = levels_)
  }

  cols <- setdiff(colnames(x), by)
  dtx <- as.data.table(x)
  dat <- dtx[, list(data=list(.SD)), by = by, .SDcols = cols]
  dat$data <- lapply(dat$data, dataset_describe)

  for(i in seq_len(nrow(dat))){
    w <- as.data.frame(dat$data[[i]])
    w[by] <- lapply(dat[i, .SD, .SDcols = by], function(z) {
      rep(z, length.out = nrow(w))
    })
    dat$data[[i]] <- w
  }
  dat <- rbindlist(dat$data)

  first_levels <- c("Min.", "1st Qu.", "Mean", "Median", "3rd Qu.",
                    "Max.")
  last_levels <- c("Missing")
  levs <- c(first_levels, setdiff(unique(dat$stat), c(first_levels, last_levels)), last_levels)
  dat$stat <- factor(dat$stat, levels = levs)
  setDF(dat)
  dat
}

dataset_describe <- function(dataset){

  w <- lapply(dataset, function(x){

    if(is.factor(x) || is.character(x)){
      z <- table(x, useNA = "always")
      names(z)[is.na(names(z))] <- "Missing"
      z <- as.data.frame(z)
      colnames(z) <- c("stat", "cts")
      z$percent <- z$cts / sum(z$cts)
      z$data_type <- "discrete"
      z
    } else if(is.numeric(x)){
      z <- c(
        "Min." = min(x, na.rm = TRUE),
        "Max." = max(x, na.rm = TRUE),
        "1st Qu." = as.double(quantile(x, probs = .25, na.rm = TRUE)),
        "3rd Qu." = as.double(quantile(x, probs = .75, na.rm = TRUE)),
        "Median" = as.double(quantile(x, probs = .5, na.rm = TRUE)),
        "Mean" = mean(x, na.rm = TRUE),
        "Missing" = NA_real_
      )
      z <- data.frame(stat = names(z), value = as.double(z),
                      cts = NA_real_, percent = NA_real_)
      z$cts[z$stat %in% "Missing"] <- sum(is.na(x))
      z$percent[z$stat %in% "Missing"] <- sum(is.na(x)) / length(x)
      z$data_type <- "continuous"
      z
    }
  })
  w <- rbindlist(w, use.names = TRUE, fill = TRUE, idcol = "variable")
  setDF(w)
  w
}

#' @export
#' @title format content for data generated with [summarizor()]
#' @param stat,data_type,value,count,percent column names
#' generated by summarizor().
format_summarizor_cols <- function(stat, data_type, value, count, percent){
  z <- character(length = length(stat))
  wcts <- !is.na(count)
  wnum <- !is.na(value)
  z[wcts] <- sprintf("%.0f (%.01f %%)", count[wcts], percent[wcts]*100)
  z[wnum] <- sprintf("%.02f", value[wnum])
  z
}

